import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const skills = [
    // ─── Programming Languages ───────────────────────────────────────────────
    "JavaScript",
    "TypeScript",
    "Java",
    "Python",
    "C",
    "C++",
    "C#",
    "Go",
    "Rust",
    "PHP",
    "Kotlin",
    "Swift",
    "Dart",
    "Ruby",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Elixir",
    "Haskell",
    "Lua",
    "Julia",
    "Assembly",
    "Bash / Shell Scripting",
    "PowerShell",
    "Objective-C",
    "F#",
    "Groovy",
    "Solidity",
    "Move",

    // ─── Frontend ────────────────────────────────────────────────────────────
    "HTML",
    "CSS",
    "Sass / SCSS",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Ant Design",
    "Chakra UI",
    "ShadCN UI",
    "React",
    "Next.js",
    "Redux",
    "Zustand",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "SvelteKit",
    "Solid.js",
    "Astro",
    "Remix",
    "Three.js",
    "D3.js",
    "Chart.js",
    "WebAssembly",
    "Progressive Web Apps (PWA)",
    "Web Components",
    "Storybook",

    // ─── Backend ─────────────────────────────────────────────────────────────
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Hono",
    "Spring Boot",
    "Hibernate",
    "Django",
    "Flask",
    "FastAPI",
    "Celery",
    "Laravel",
    "Symfony",
    "ASP.NET Core",
    "Ruby on Rails",
    "Phoenix",
    "Gin",
    "Fiber",
    "gRPC",
    "tRPC",
    "WebSockets",
    "Server-Sent Events",

    // ─── Databases ────────────────────────────────────────────────────────────
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "MongoDB",
    "Redis",
    "SQLite",
    "Oracle Database",
    "Microsoft SQL Server",
    "Firebase Realtime Database",
    "Firestore",
    "Cassandra",
    "DynamoDB",
    "Couchbase",
    "Elasticsearch",
    "Neo4j",
    "InfluxDB",
    "TimescaleDB",
    "Supabase",
    "PlanetScale",
    "Neon",

    // ─── ORM / Query Builders ─────────────────────────────────────────────────
    "Prisma",
    "Mongoose",
    "Sequelize",
    "TypeORM",
    "Drizzle ORM",
    "SQLAlchemy",
    "GORM",
    "Knex.js",

    // ─── DevOps / Cloud ───────────────────────────────────────────────────────
    "Docker",
    "Docker Compose",
    "Kubernetes",
    "Helm",
    "AWS",
    "AWS EC2",
    "AWS S3",
    "AWS Lambda",
    "AWS ECS",
    "AWS RDS",
    "Azure",
    "Azure DevOps",
    "Google Cloud Platform (GCP)",
    "Google Cloud Run",
    "Firebase",
    "Vercel",
    "Netlify",
    "Heroku",
    "DigitalOcean",
    "Render",
    "Railway",
    "Nginx",
    "Apache HTTP Server",
    "Linux",
    "Ubuntu",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI/CD",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "ArgoCD",
    "Terraform",
    "Ansible",
    "Pulumi",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "Sentry",

    // ─── APIs / Auth ──────────────────────────────────────────────────────────
    "REST API",
    "GraphQL",
    "Apollo GraphQL",
    "JWT Authentication",
    "OAuth 2.0",
    "OpenID Connect",
    "Passport.js",
    "Auth0",
    "Clerk",
    "Firebase Auth",
    "Socket.IO",
    "WebRTC",
    "OpenAPI / Swagger",
    "Postman",
    "Insomnia",

    // ─── Testing ──────────────────────────────────────────────────────────────
    "Jest",
    "Vitest",
    "Mocha",
    "Chai",
    "Cypress",
    "Playwright",
    "Selenium",
    "Puppeteer",
    "React Testing Library",
    "JUnit",
    "PyTest",
    "K6 (Load Testing)",
    "Locust",

    // ─── Version Control / Collaboration ──────────────────────────────────────
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Linear",
    "Confluence",
    "Notion",
    "Slack",
    "Trello",

    // ─── Mobile Development ───────────────────────────────────────────────────
    "Android Development",
    "iOS Development",
    "React Native",
    "Flutter",
    "Expo",
    "Jetpack Compose",
    "SwiftUI",
    "UIKit",
    "Kotlin Multiplatform",
    "Capacitor",
    "Ionic",
    "App Store Optimization (ASO)",
    "Firebase Cloud Messaging (FCM)",

    // ─── AI / ML / Data Science ───────────────────────────────────────────────
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Reinforcement Learning",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "XGBoost",
    "LightGBM",
    "Hugging Face Transformers",
    "LangChain",
    "LlamaIndex",
    "OpenAI API",
    "Gemini API",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Jupyter Notebooks",
    "Apache Spark",
    "Hadoop",
    "Databricks",
    "MLflow",
    "Weights & Biases",
    "Vertex AI",
    "SageMaker",
    "Prompt Engineering",
    "RAG (Retrieval-Augmented Generation)",
    "Vector Databases",
    "Pinecone",
    "Weaviate",
    "Qdrant",

    // ─── Data Engineering ─────────────────────────────────────────────────────
    "Apache Kafka",
    "Apache Airflow",
    "dbt",
    "Apache Flink",
    "ETL Pipelines",
    "Data Warehousing",
    "Snowflake",
    "BigQuery",
    "Amazon Redshift",
    "Power BI",
    "Tableau",
    "Looker",
    "Metabase",

    // ─── Blockchain / Web3 ────────────────────────────────────────────────────
    "Blockchain Development",
    "Smart Contracts",
    "Solidity",
    "Hardhat",
    "Foundry",
    "Ethers.js",
    "Web3.js",
    "IPFS",
    "NFT Development",
    "DeFi",
    "Chainlink",
    "Polygon",
    "Ethereum",

    // ─── Cybersecurity ────────────────────────────────────────────────────────
    "Cybersecurity",
    "Penetration Testing",
    "Ethical Hacking",
    "Network Security",
    "Application Security",
    "OWASP",
    "Burp Suite",
    "Wireshark",
    "Metasploit",
    "SIEM",
    "Zero Trust Architecture",
    "Cryptography",
    "PKI",

    // ─── AR / VR / Game Dev ───────────────────────────────────────────────────
    "Unity",
    "Unreal Engine",
    "AR Development",
    "VR Development",
    "Mixed Reality",
    "OpenGL",
    "Vulkan",
    "WebGL",
    "Blender",

    // ─── IoT / Embedded ───────────────────────────────────────────────────────
    "IoT Development",
    "Embedded Systems",
    "Arduino",
    "Raspberry Pi",
    "MQTT",
    "Firmware Development",
    "RTOS",
    "Edge Computing",

    // ─── Software Engineering Concepts ────────────────────────────────────────
    "Data Structures",
    "Algorithms",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "System Design",
    "Microservices Architecture",
    "Event-Driven Architecture",
    "Design Patterns",
    "Domain-Driven Design (DDD)",
    "Test-Driven Development (TDD)",
    "SOLID Principles",
    "Operating Systems",
    "DBMS",
    "Computer Networks",
    "Distributed Systems",
    "Concurrency & Multithreading",
    "Compiler Design",
    "High-Performance Computing",

    // ─── Tools & Productivity ─────────────────────────────────────────────────
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Prettier",
    "Turborepo",
    "Nx",
    "pnpm",
    "Yarn",
    "npm",
    "Make / Makefile",
    "Linux CLI",
    "tmux",
    "Vim / Neovim",
    "VS Code",

    // ─── UI/UX & Design ───────────────────────────────────────────────────────
    "Figma",
    "Adobe XD",
    "Sketch",
    "UI/UX Design",
    "Responsive Design",
    "Accessibility (a11y)",
    "User Research",
    "Prototyping",
    "Wireframing",
    "Design Systems",
  ];

  let count = 0;

  for (const skill of skills) {
    await prisma.skill.upsert({
      where: { name: skill },
      update: {},
      create: { name: skill },
    });
    count++;
  }

  console.log(`✅ Skills seeded: ${count} skills upserted. Total in list: ${skills.length}`);

}

main()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
  });